#!/bin/bash

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Get the list of processes using the ps command
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest | tail -n +2

